### ISSUE TITLE
Playing a folder

### ISSUE THREAD

**Issue by parszab** [molobrakos/lms-mobileskin#10]
Sorry for the lame question, but: is there a way to play a folder? I just installed the plugin, and tried everything to play an album from the folder view, but I could only play single files. Did'n even find a way to add them to the playlist. Am I missing something obvious?

Thanks,
Szabolcs

**Comment by molobrakos** [comment]
Sorry, not implemented (yet). :-(

**Comment by parszab** [comment]
Oh I see, thx.

**Comment by molobrakos** [comment]
Let's keep the issue open as a reminder to fix it :-)

**Comment by DrSky2007** [comment]
+1 from me. I am looking forward to see this feature in an upcoming release. This is the only thing I am missing in your almost perfect skin! Thanks for the work so far!
