### ISSUE TITLE
improve space usage

### ISSUE THREAD

**Issue by doka2212** [molobrakos/lms-mobileskin#2]
Most control icons are very small. 
There is also much unused space (especially at landscape).

Maybe it's better to reduce the number of controls. 
Maybe inspire by the design of volumio, moodeaudio or runeaudio.

**Comment by molobrakos** [comment]
You are correct! The goal is to improve the stylesheet and adapt the application to whatever screen resolution it is runing on. CSS also makes it possibe to show/hide controls depending on the resolution/available space.
Do you have knowledge in HTML/CSS? I would gladly accept a Pull Request that improved the user experience in this area!

**Comment by doka2212** [comment]
Thanks for the response. 
I have some experience with CSS/HTML but I am not so familiar with bootstrap and I ma not a disigner. 
So I think there is a bad	cost-value ratio for pull request for me.

**Comment by molobrakos** [comment]
Feel free to provide a patch/code if you have any suggestion on how to improve the user experience / design in this area. Closing this for now.
