### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by TFW278** [molobrakos/lms-mobileskin#3]
Is there any way you could adjust Class settings in order to work with IE? I am using it for Homeseer and the Webserver renders everything in IE. Changing the registry to force IE11 helped render a little bit more, but most of the functionality is still missing!

This change would help 1,000's of HomeSeer Users that use LMS for music which is most.

I've been trying to tinker around, even tried the old Google ChromeFrame project, but have not had any success.

**Comment by molobrakos** [comment]
Thanks for using and thanks for feedback!
I am not sure what you mean by "adjust Class settings"?
I have no plans on implementing support for IE myself, the main reason is that I don't have access to any IE installation for developing/testing.
I would however accept any reasonably small patch that improved support for IE users if you would like to help out.
