### ISSUE TITLE
Todo: Create a plugin

### ISSUE THREAD

**Issue by oweitman** [molobrakos/lms-mobileskin#4]
i have made a script to update the plugin and repository files
you can check my script on https://github.com/oweitman/LMS-shoutcast
1. copy install.xml public.xml and _create_pkg.sh
2. adjust data in install.xml
3. adjust data in public.xml
4. adjust some hardcoded parameters in _create_pkg.sh 
5. see readme, how to point the LMS to the repository-file

all tools used are standard linux tools (sed, zip, awk, sha1sum)

**Comment by molobrakos** [comment]
Many thanks! Will have a look!

**Comment by oweitman** [comment]
hi
i saw you tried the script.
one last thing you forgot.
you have to provide the zip-file 
lms-mobileskin.zip
in the main directory of your github-repository
the following link (inside the public.xml) point to this file.
https://raw.githubusercontent.com/molobrakos/lms-mobileskin/master/lms-mobileskin.zip

**Comment by molobrakos** [comment]
Yes, I was actually playing around with Github's system for creating releases: https://developer.github.com/v3/repos/releases/#create-a-release

Btw, do you have any idea what` install.xml `should look like in my case, since it is not a proper plugin (no `Plugin.pm` file), just a skin (should only create a subdir in the server `HTML` directory). Should I just skip the `module` tag (i.e. in your case `<module>Plugins::NewShoutcast::Plugin</module>`)

**Comment by oweitman** [comment]
check the following repository for a skin plugin. 

https://github.com/millerdev/lms-ultralight/tree/master/UltralightSkin

he use a Plugin.pm for some initializing. maybe you need some similar.
i checked the source of PluginManager.pm
if the key <module> didnt exist the PluginManager skips the initializing of the modules

**Comment by oweitman** [comment]
it seems that LMS use a directory overlay or directory inheritance structure
in a plugin you didnt need to create new subfolders under the Main- HTML directory
you only provide the folders inside the Plugin structure and LMS integrate this

**Comment by molobrakos** [comment]
Thanks, I wasn't aware of that skin - it looks very nice! :-)

**Comment by oweitman** [comment]
ok, i made several changes.
now i have a functional plugin
https://github.com/oweitman/lms-mobileskin
but i didnt use your build system. i use my _create_pkg.sh script
i think github restrict download from releases only to browsers. i have to use the code-area 
if you have questions, feel free

**Comment by molobrakos** [comment]
Thanks for all your help! I believe I have got it all sorted out now.
I am able to install the plugin by adding the repo http://raw.githubusercontent.com/molobrakos/lms-mobileskin/master/public.xml and have it automatically updated.
Please test/verify if you have time.
